entity counter is
generic
(
	start	: integer := 0,
	end_val	: integer := 200,
	duration	: integer
);
port
(
	clk	: In  std_logic,
	reset	: In  std_logic,
	signal	: Out std_logic_vector(31 downto 0),
	count	: Out std_logic_vector(18 downto 0)
);
end counter;

architecture implementation of counter is
	-- declarations
begin
	-- contents
-- Autogenerated asynchronously asserted, synchronously deasserted signal synchronizer.
process ({clk}, rst)
begin
    if rst = '1' then
        sync1_sync_stages <= (others => '1');
    elsif rising_edge({{clk}}) then
        sync1_sync_stages(1) <= '0';
        for i in 2 to sync1_STAGES loop
            sync1_sync_stages(i) <= sync1_sync_stages(i-1);
        end loop;
    end if;
end process;

rst_out <= sync1_sync_stages(sync1_STAGES)

-- ASYNC_REG attribute on each flip-flop
for i in 1 to sync1_STAGES generate
    attribute ASYNC_REG : string;
    attribute ASYNC_REG of sync1_sync_stages(i) : signal is "TRUE";
end generate;
-- End of Sync-Async synchronizer.
end implementation;

